M48
; DRILL file {KiCad 8.0.8-8.0.8-0~ubuntu22.04.1} date 2025-02-21T02:47:37+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-21T02:47:37+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8-8.0.8-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.8705Y-4.7226
X6.098Y-4.7226
M30
