M48
; DRILL file {KiCad 9.0.2-9.0.2-0~ubuntu24.04.1} date 2025-05-21T01:19:16+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-21T01:19:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-9.0.2-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.8705Y-4.7226
X6.098Y-4.7226
M30
