M48
; DRILL file {KiCad 9.0.2-9.0.2-0~ubuntu24.04.1} date 2025-07-25T01:35:49+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-25T01:35:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2-9.0.2-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X5.9221Y-4.5719
X6.1497Y-4.5719
M30
